public class ArthimaticCalculations {
    public integer Addition(integer x, integer y) {
        integer z = x + y;
        return z;
    }
    public integer Subtraction(integer x, integer y){
        integer z = x - y;
        return z;
    }
    public integer Multiplication(integer w, integer x, integer y){
        integer z = w*x*y;
        return z;
    }
    public string concatStrings(string a, string b){
        string z = a +' & ' +b;
        return z;

}
}