List<integer> tempList = new list<integer>{5,21,15,99,77,101}; //this will add all these elements by default in the LIST.
integer sum1 = ListDemo2.add(tempList);
system.debug('sum1 is ' + sum1);

List<String> ls = new List<String>{'list', 'set', 'map', 'array'};
ListDemo2.iterateListString(ls);

List<String> ls2 = new List<String>{'car', 'bus', 'plane', 'truck'};

system.debug(ListDemo2.add(ls2));

ListDemo2.iterateListString99();
